export interface Property {
  id: number;
  title: string;
  location: string;
  price: number;
  beds: number;
  baths: number;
  sqm: number;
  tag: string | null;
  image: string;
  type: 'piso' | 'chalet' | 'villa' | 'adosado' | 'duplex';
  piscina: boolean;
  garaje: boolean;
  ascensor: boolean;
  noHipotecable: boolean;
}

export const properties: Property[] = [
  {
    id: 1,
    title: "Chalet Independiente con Piscina",
    location: "Palomares del Río, Aljarafe",
    price: 485000,
    beds: 4,
    baths: 3,
    sqm: 280,
    tag: "REBAJADO -8%",
    image: "https://images.unsplash.com/photo-1757439402359-aed14d39fc1b?w=700&h=500&fit=crop&auto=format",
    type: "chalet",
    piscina: true,
    garaje: true,
    ascensor: false,
    noHipotecable: false,
  },
  {
    id: 2,
    title: "Ático con Gran Terraza",
    location: "Mairena del Aljarafe",
    price: 320000,
    beds: 3,
    baths: 2,
    sqm: 145,
    tag: null,
    image: "https://images.unsplash.com/photo-1631510390389-c1e4fb20ff31?w=700&h=500&fit=crop&auto=format",
    type: "piso",
    piscina: true,
    garaje: true,
    ascensor: true,
    noHipotecable: false,
  },
  {
    id: 3,
    title: "Villa de Lujo con Parcela Privada",
    location: "Tomares",
    price: 750000,
    beds: 5,
    baths: 4,
    sqm: 420,
    tag: "EXCLUSIVA",
    image: "https://images.unsplash.com/photo-1760681556931-52ee66c4d88f?w=700&h=500&fit=crop&auto=format",
    type: "villa",
    piscina: true,
    garaje: true,
    ascensor: false,
    noHipotecable: true,
  },
  {
    id: 4,
    title: "Piso Renovado en el Centro",
    location: "Sevilla Capital",
    price: 275000,
    beds: 2,
    baths: 1,
    sqm: 89,
    tag: "VENDIDO",
    image: "https://images.unsplash.com/photo-1665249934445-1de680641f50?w=700&h=500&fit=crop&auto=format",
    type: "piso",
    piscina: false,
    garaje: false,
    ascensor: true,
    noHipotecable: false,
  },
  {
    id: 5,
    title: "Casa Adosada con Jardín",
    location: "Bormujos",
    price: 395000,
    beds: 3,
    baths: 2,
    sqm: 195,
    tag: "REBAJADO -5%",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=700&h=500&fit=crop&auto=format",
    type: "adosado",
    piscina: false,
    garaje: true,
    ascensor: false,
    noHipotecable: false,
  },
  {
    id: 6,
    title: "Dúplex con Jardín Privado",
    location: "San Juan de Aznalfarache",
    price: 310000,
    beds: 3,
    baths: 2,
    sqm: 165,
    tag: null,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=700&h=500&fit=crop&auto=format",
    type: "duplex",
    piscina: false,
    garaje: true,
    ascensor: false,
    noHipotecable: false,
  },
  {
    id: 7,
    title: "Villa Mediterránea con Vistas al Campo",
    location: "Valencina de la Concepción",
    price: 890000,
    beds: 6,
    baths: 5,
    sqm: 560,
    tag: "REBAJADO -12%",
    image: "https://images.unsplash.com/photo-1781456016988-04806c42c260?w=700&h=500&fit=crop&auto=format",
    type: "villa",
    piscina: true,
    garaje: true,
    ascensor: false,
    noHipotecable: true,
  },
  {
    id: 8,
    title: "Apartamento Moderno con Terraza",
    location: "Camas",
    price: 195000,
    beds: 2,
    baths: 1,
    sqm: 78,
    tag: null,
    image: "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=700&h=500&fit=crop&auto=format",
    type: "piso",
    piscina: false,
    garaje: false,
    ascensor: true,
    noHipotecable: false,
  },
  {
    id: 9,
    title: "Chalet con Piscina Comunitaria",
    location: "Gines",
    price: 420000,
    beds: 4,
    baths: 3,
    sqm: 245,
    tag: null,
    image: "https://images.unsplash.com/photo-1670589953882-b94c9cb380f5?w=700&h=500&fit=crop&auto=format",
    type: "chalet",
    piscina: true,
    garaje: true,
    ascensor: false,
    noHipotecable: false,
  },
];

export const formatPrice = (p: number) =>
  p.toLocaleString('es-ES', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 });
