export interface Property {
  id: number;
  title: string;
  location: string;
  price: number;
  beds: number;
  baths: number;
  sqm: number;
  tag: string | null;
  image: string;
  gallery: string[];
  type: 'piso' | 'chalet' | 'villa' | 'adosado' | 'duplex';
  piscina: boolean;
  garaje: boolean;
  ascensor: boolean;
  noHipotecable: boolean;
  description: string;
  año?: number;
  planta?: string;
  orientacion?: string;
  certificadoEnergetico?: string;
}

export const properties: Property[] = [
  {
    id: 1,
    title: "Chalet Independiente con Piscina",
    location: "Palomares del Río, Aljarafe",
    price: 485000,
    beds: 4,
    baths: 3,
    sqm: 280,
    tag: "REBAJADO -8%",
    image: "https://images.unsplash.com/photo-1757439402359-aed14d39fc1b?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop&auto=format",
    ],
    type: "chalet",
    piscina: true,
    garaje: true,
    ascensor: false,
    noHipotecable: false,
    año: 2005,
    orientacion: "Sur",
    certificadoEnergetico: "C",
    description: "Espectacular chalet independiente ubicado en una de las zonas más exclusivas de Palomares del Río. La propiedad se distribuye en dos plantas con amplios salones llenos de luz natural. Cuenta con piscina privada rodeada de jardín mediterráneo, garaje para dos vehículos y una terraza panorámica desde la planta superior. La cocina ha sido completamente renovada con electrodomésticos de última generación. Todos los dormitorios tienen armarios empotrados y el dormitorio principal dispone de vestidor y baño en suite. Ubicación privilegiada a escasos metros de todos los servicios y con fácil acceso a Sevilla capital.",
  },
  {
    id: 2,
    title: "Ático con Gran Terraza",
    location: "Mairena del Aljarafe",
    price: 320000,
    beds: 3,
    baths: 2,
    sqm: 145,
    tag: null,
    image: "https://images.unsplash.com/photo-1631510390389-c1e4fb20ff31?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1599619351208-3e6c839d6828?w=800&h=600&fit=crop&auto=format",
    ],
    type: "piso",
    piscina: true,
    garaje: true,
    ascensor: true,
    noHipotecable: false,
    año: 2018,
    planta: "Ático (última planta)",
    orientacion: "Sureste",
    certificadoEnergetico: "B",
    description: "Magnífico ático de nueva construcción con una terraza privada de 60 m² desde la que se disfrutan unas vistas excepcionales al Aljarafe. El interior combina materiales nobles —suelos de microcemento, cocina de diseño italiano y carpintería de aluminio de alta gama— con una distribución abierta muy luminosa. La urbanización dispone de piscina comunitaria, zonas ajardinadas y vigilancia 24h. El garaje incluido tiene punto de recarga para vehículo eléctrico. Una oportunidad única para quienes buscan vivir con todas las comodidades y sin renunciar a la ciudad.",
  },
  {
    id: 3,
    title: "Villa de Lujo con Parcela Privada",
    location: "Tomares",
    price: 750000,
    beds: 5,
    baths: 4,
    sqm: 420,
    tag: "EXCLUSIVA",
    image: "https://images.unsplash.com/photo-1760681556931-52ee66c4d88f?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1592595896551-12b371d546d5?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1553653924-39b70295f8da?w=800&h=600&fit=crop&auto=format",
    ],
    type: "villa",
    piscina: true,
    garaje: true,
    ascensor: false,
    noHipotecable: true,
    año: 2012,
    orientacion: "Sur-Oeste",
    certificadoEnergetico: "B",
    description: "Propiedad de referencia en el exclusivo municipio de Tomares. Esta villa de diseño contemporáneo ocupa una parcela privada de 800 m² con jardín tropical, piscina infinity y zona de barbacoa. El interior alberga cinco dormitorios —tres de ellos con baño en suite—, un gran salón-comedor de doble altura, sala de cine, bodega climatizada y gimnasio. Los acabados son de la más alta calidad: suelos de mármol, domótica integral y sistema de climatización por aerotermia. Garaje cerrado para tres vehículos. Oportunidad única, no hipotecable. Precio negociable solo para compradores serios.",
  },
  {
    id: 4,
    title: "Piso Renovado en el Centro",
    location: "Sevilla Capital",
    price: 275000,
    beds: 2,
    baths: 1,
    sqm: 89,
    tag: "VENDIDO",
    image: "https://images.unsplash.com/photo-1665249934445-1de680641f50?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop&auto=format",
    ],
    type: "piso",
    piscina: false,
    garaje: false,
    ascensor: true,
    noHipotecable: false,
    año: 1970,
    planta: "3ª planta",
    orientacion: "Este",
    certificadoEnergetico: "D",
    description: "Piso completamente reformado en el corazón del casco histórico de Sevilla. La reforma integral realizada en 2023 incluye nueva instalación eléctrica, fontanería, suelos de tarima y cocina americana abierta al salón. Edificio con ascensor y portero automático. La distribución aprovecha al máximo los 89 m² con dos dormitorios dobles, salón amplio y baño con ducha rain shower. A escasos metros de las principales arterias comerciales y de transporte. Actualmente vendido, pero sírvete de inspiración para propiedades similares disponibles.",
  },
  {
    id: 5,
    title: "Casa Adosada con Jardín",
    location: "Bormujos",
    price: 395000,
    beds: 3,
    baths: 2,
    sqm: 195,
    tag: "REBAJADO -5%",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&h=600&fit=crop&auto=format",
    ],
    type: "adosado",
    piscina: false,
    garaje: true,
    ascensor: false,
    noHipotecable: false,
    año: 2003,
    orientacion: "Sur",
    certificadoEnergetico: "C",
    description: "Casa adosada de esquina en urbanización tranquila de Bormujos, muy bien comunicada con Sevilla por autovía y metro. La propiedad cuenta con jardín privado de 80 m² en la parte trasera, perfecto para disfrutar del clima sevillano. La planta baja alberga el salón-comedor, cocina independiente equipada, aseo de cortesía y acceso directo al garaje. En la planta alta encontramos tres dormitorios con amplios armarios y dos baños completos. El dormitorio principal tiene acceso a una terraza privada con vistas al parque cercano. Precio rebajado recientemente para facilitar venta inmediata.",
  },
  {
    id: 6,
    title: "Dúplex con Jardín Privado",
    location: "San Juan de Aznalfarache",
    price: 310000,
    beds: 3,
    baths: 2,
    sqm: 165,
    tag: null,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop&auto=format",
    ],
    type: "duplex",
    piscina: false,
    garaje: true,
    ascensor: false,
    noHipotecable: false,
    año: 2009,
    planta: "Planta baja + 1ª",
    orientacion: "Oeste",
    certificadoEnergetico: "C",
    description: "Espléndido dúplex con jardín privado de uso exclusivo en San Juan de Aznalfarache, a minutos de Sevilla capital. La vivienda se distribuye en dos plantas comunicadas por escalera interior: en la baja, gran salón con acceso directo al jardín, cocina equipada y garaje; en la alta, tres dormitorios, dos baños y una terraza descubierta. El jardín privado de 60 m² está completamente vallado y cuenta con zona de césped y pérgola. La urbanización ofrece zonas verdes comunitarias. Ideal para familias que buscan la comodidad de un chalet con el precio de un piso.",
  },
  {
    id: 7,
    title: "Villa Mediterránea con Vistas al Campo",
    location: "Valencina de la Concepción",
    price: 890000,
    beds: 6,
    baths: 5,
    sqm: 560,
    tag: "REBAJADO -12%",
    image: "https://images.unsplash.com/photo-1781456016988-04806c42c260?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1553653924-39b70295f8da?w=800&h=600&fit=crop&auto=format",
    ],
    type: "villa",
    piscina: true,
    garaje: true,
    ascensor: false,
    noHipotecable: true,
    año: 2008,
    orientacion: "Sur-Este",
    certificadoEnergetico: "B",
    description: "Villa de estilo mediterráneo en una de las parcelas más privilegiadas de Valencina de la Concepción, con impresionantes vistas al Aljarafe y la campiña sevillana. Con 560 m² construidos sobre una parcela de 1.200 m², la propiedad ofrece seis dormitorios —cuatro en suite—, salón de más de 80 m², sala de juegos, despacho y cocina de chef. Exteriores de ensueño con piscina, zona de spa, huerto propio y cochera para cuatro vehículos. El precio ha sido ajustado un 12% para una venta ágil. Propiedad no hipotecable, compra solo al contado o con financiación propia.",
  },
  {
    id: 8,
    title: "Apartamento Moderno con Terraza",
    location: "Camas",
    price: 195000,
    beds: 2,
    baths: 1,
    sqm: 78,
    tag: null,
    image: "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1599619351208-3e6c839d6828?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&h=600&fit=crop&auto=format",
    ],
    type: "piso",
    piscina: false,
    garaje: false,
    ascensor: true,
    noHipotecable: false,
    año: 2020,
    planta: "2ª planta",
    orientacion: "Sur",
    certificadoEnergetico: "A",
    description: "Apartamento de nueva construcción con acabados modernos y terraza privada de 18 m² en Camas, muy bien comunicado con Sevilla mediante metro. El diseño interior apuesta por la luminosidad y la funcionalidad: cocina abierta tipo isla, suelos de porcelánico grande formato y ventanas de doble acristalamiento con rotura de puente térmico. Ambos dormitorios tienen armario empotrado a medida. Certificado energético A, con instalación de aerotermia que reduce drásticamente los consumos. Perfecto como primera vivienda o inversión de alquiler con rentabilidad estimada del 5%.",
  },
  {
    id: 9,
    title: "Chalet con Piscina Comunitaria",
    location: "Gines",
    price: 420000,
    beds: 4,
    baths: 3,
    sqm: 245,
    tag: null,
    image: "https://images.unsplash.com/photo-1670589953882-b94c9cb380f5?w=1200&h=800&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&h=600&fit=crop&auto=format",
    ],
    type: "chalet",
    piscina: true,
    garaje: true,
    ascensor: false,
    noHipotecable: false,
    año: 2001,
    orientacion: "Sur-Oeste",
    certificadoEnergetico: "C",
    description: "Chalet de cuatro dormitorios en urbanización cerrada de Gines con piscina y zonas deportivas comunitarias. La planta baja cuenta con un generoso salón-comedor con chimenea, cocina independiente totalmente equipada, despensa, aseo y garaje para dos coches. En la planta primera se ubican los cuatro dormitorios —el principal con baño en suite y vestidor— y un baño de uso compartido. El jardín privado está perfectamente mantenido con zona de barbacoa y pérgola. La urbanización ofrece seguridad 24h, piscina olímpica, padel y parque infantil. Un entorno idílico para familias.",
  },
];

export const formatPrice = (p: number) =>
  p.toLocaleString('es-ES', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 });
